# Intro to Machine Learning

![elgifderigor](https://media.giphy.com/media/NsBknNwmmWE8WU1q2U/giphy.gif)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Some-concepts" data-toc-modified-id="Some-concepts-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Some concepts</a></span><ul class="toc-item"><li><span><a href="#Estimators" data-toc-modified-id="Estimators-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Estimators</a></span></li><li><span><a href="#Bias-Error" data-toc-modified-id="Bias-Error-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Bias Error</a></span></li><li><span><a href="#Variance-Error" data-toc-modified-id="Variance-Error-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Variance Error</a></span></li></ul></li><li><span><a href="#Types-of-Machine-Learning" data-toc-modified-id="Types-of-Machine-Learning-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Types of Machine Learning</a></span></li><li><span><a href="#Features" data-toc-modified-id="Features-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Features</a></span></li><li><span><a href="#Underfitting-and-Overfitting" data-toc-modified-id="Underfitting-and-Overfitting-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Underfitting and Overfitting</a></span></li><li><span><a href="#Let's-do-it?" data-toc-modified-id="Let's-do-it?-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Let's do it?</a></span><ul class="toc-item"><li><span><a href="#Let's-practice-ML-with-a-regression-example" data-toc-modified-id="Let's-practice-ML-with-a-regression-example-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Let's practice ML with a regression example</a></span></li><li><span><a href="#We-load-a-dataset" data-toc-modified-id="We-load-a-dataset-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>We load a dataset</a></span></li><li><span><a href="#Train-/-Test-Split---What-is-this?" data-toc-modified-id="Train-/-Test-Split---What-is-this?-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Train / Test Split - What is this?</a></span></li><li><span><a href="#Preparing-data-for-train-test-split" data-toc-modified-id="Preparing-data-for-train-test-split-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Preparing data for train test split</a></span></li><li><span><a href="#Optional-train-test-split-parameters" data-toc-modified-id="Optional-train-test-split-parameters-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Optional train test split parameters</a></span></li><li><span><a href="#We-already-have-the-dataset-divided,-now-we-are-going-to-import-a-model-and-train-it" data-toc-modified-id="We-already-have-the-dataset-divided,-now-we-are-going-to-import-a-model-and-train-it-5.6"><span class="toc-item-num">5.6&nbsp;&nbsp;</span>We already have the dataset divided, now we are going to import a model and train it</a></span></li><li><span><a href="#We-create-our-predictions" data-toc-modified-id="We-create-our-predictions-5.7"><span class="toc-item-num">5.7&nbsp;&nbsp;</span>We create our predictions</a></span></li><li><span><a href="#We-measure-our-model" data-toc-modified-id="We-measure-our-model-5.8"><span class="toc-item-num">5.8&nbsp;&nbsp;</span>We measure our model</a></span><ul class="toc-item"><li><span><a href="#Mini-checkpoint" data-toc-modified-id="Mini-checkpoint-5.8.1"><span class="toc-item-num">5.8.1&nbsp;&nbsp;</span>Mini-checkpoint</a></span></li></ul></li></ul></li><li><span><a href="#The-machine-learning-process" data-toc-modified-id="The-machine-learning-process-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>The machine learning process</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Example-with-new-data" data-toc-modified-id="Example-with-new-data-6.0.1"><span class="toc-item-num">6.0.1&nbsp;&nbsp;</span>Example with new data</a></span></li></ul></li></ul></li><li><span><a href="#Extra!-Training-different-models-at-the-same-time" data-toc-modified-id="Extra!-Training-different-models-at-the-same-time-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Extra! Training different models at the same time</a></span><ul class="toc-item"><li><span><a href="#Store-all-the-models-we-are-going-to-train-in-a-dictionary" data-toc-modified-id="Store-all-the-models-we-are-going-to-train-in-a-dictionary-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Store all the models we are going to train in a dictionary</a></span></li><li><span><a href="#Iterate-over-the-models-to-train-them" data-toc-modified-id="Iterate-over-the-models-to-train-them-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Iterate over the models to train them</a></span></li></ul></li><li><span><a href="#Feature-Selection" data-toc-modified-id="Feature-Selection-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Feature Selection</a></span><ul class="toc-item"><li><span><a href="#We-make-CV-to-a-single-model" data-toc-modified-id="We-make-CV-to-a-single-model-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>We make CV to a single model</a></span></li><li><span><a href="#CV-looping-through-all-models" data-toc-modified-id="CV-looping-through-all-models-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>CV looping through all models</a></span></li></ul></li><li><span><a href="#Summary" data-toc-modified-id="Summary-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Summary</a></span></li></ul></div>

![sklearn](../images/ext_sklearn.jpeg)

## Some concepts
To understand how a machine learning algorithm learns from data to predict an outcome, it is essential to understand the underlying concepts that go into training an algorithm.

### Estimators
Estimate is a statistical term for finding some estimate of an unknown parameter, given some data. Point estimation is the attempt to provide the best prediction of some quantity of interest.
The amount of interest can be:
 - A single parameter
 - A vector of parameters - for example, the weights in linear regression
 - A full function

### Bias Error

It is the difference between the expected prediction of our model and the true values. Although in the end our goal is always to build models that can predict data very close to the true values, it is not always that easy because some algorithms are simply too rigid to learn complex signals from the data set.

Imagine fitting a linear regression to a data set that has a non-linear pattern, no matter how many more observations you collect, a linear regression will not be able to model the curves on that data. This is known as underfitting.

In general, parametric algorithms like linear regression have a high bias that makes them quick to learn and easier to understand, but generally less flexible. In turn, they have a lower predictive performance in complex problems.

### Variance Error

It refers to the amount that the estimate of the objective function will change if different training data is used. The objective function is estimated from the training data by a Machine Learning algorithm, so we should expect the algorithm to have some variance. Ideally it shouldn't change too much from one training dataset to another, which means the algorithm is good at choosing the hidden underlying mapping between the input and output variables.

Machine learning algorithms that have a large variance are heavily influenced by the details of the training data, this means that the details of the training influence the number and types of parameters used to characterize the mapping function.

Generally, non-parametric machine learning algorithms that have a lot of flexibility have a lot of variation.

- Low variance: suggests small changes in the estimate of the objective function with changes in the training data set.
- High variance: suggests large changes in the estimate of the objective function with changes in the training data set.
Low variance machine learning algorithms include: linear regression, linear discriminant analysis, and logistic regression.

On the other hand, the algorithms with high variance are: decision trees, k-nearest neighbors and support vector machines.

<img src="https://nvsyashwanth.github.io/machinelearningmaster/assets/images/bias_variance.jpg" width="400">

## Types of Machine Learning
- **Supervised**
The model is trained with labeled data, that is, with data whose basic truth is known. When presented with data and a label, the model infers patterns.

- **Unsupervised**
There are no basic truths. The model looks for previously undetected patterns, with which to separate the different data points into different clusters.

- **Reinforcement**
There is also no basic truth. The model's action is valued and a reward or punishment is given accordingly. The goal of the model is to get as many rewards as possible.

## Features
- **Features** are independent individual variables that act as input to your system. Prediction models use features to
make predictions.

- **Target**
The goal is the output of the input variables. They can be the individual classes to which the input variables are assigned in the case of a classification problem or the range of output values ​​in a regression problem.

## Underfitting and Overfitting
Splitting a data set can also be important to detect if your model suffers from one of two common problems, called underfitting and overfitting:

- **Underfitting** is usually the consequence of a model being unable to encapsulate relationships between data. For example, this can occur when trying to represent nonlinear relationships with a linear model. Underfitted models are likely to perform poorly on both the training and test sets.


- **Overfitting** usually occurs when a model has an excessively complex structure and learns both relationships between data and noise. These models tend to have poor generalization ability. Although they work well with training data, they tend to perform poorly with unseen (test) data.

<img src="https://community.alteryx.com/t5/image/serverpage/image-id/52874iE986B6E19F3248CF?v=v2" width="500">

Bias and variance in machine learning --> https://www.analyticslane.com/2019/05/24/the-concepts-of-bias-and-variance-in-machine-learning/

## Let's do it?

### Let's practice ML with a regression example

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
from sklearn.datasets import load_boston

### We load a dataset

In [3]:
#help(load_boston)

In [4]:
boston = pd.DataFrame(load_boston().data, columns=load_boston().feature_names)

In [5]:
boston

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [6]:
boston["MEDV"] = load_boston().target

In [7]:
boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [8]:
# CSV: hours, music, grades
# predict?: 
# processing/cleaning
# find the line that decribes data: fit / train
# predict

### Train / Test Split - What is this?

<img src="https://www.dataquest.io/wp-content/uploads/kaggle_train_test_split.svg" width="500">

The training-test split is a technique for evaluating the performance of a machine learning algorithm.

It can be used for classification or regression problems and can be used for any supervised learning algorithm.

The procedure consists of taking a data set and dividing it into two subsets. The first subset is used to fit the model and is called the training data set. The second subset is not used to train the model; instead, the model is given the input from the dataset, then predictions are made and compared to expected values. This second data set is called the test data set.

- Training dataset: Used to fit the machine learning model.
- Test dataset: Used to evaluate the fitted machine learning model.
The goal is to estimate the performance of the machine learning model with new data: data not used to train the model.

This is how we hope to use the model in practice. That is, fit it on the available data with known inputs and outputs, and then make predictions about new examples in the future where we don't have the expected output or target values.

The training-test procedure is adequate when a sufficiently large data set is available.

### Preparing data for train test split

In [9]:
boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
# X, y
# X: features
# y: target variable

In [12]:
boston.sample()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
195  0.01381  80.0   0.46   0.0  0.422  7.875  32.0  5.6484  4.0  255.0   

     PTRATIO       B  LSTAT  MEDV  
195     14.4  394.23   2.97  50.0

In [13]:
X = boston.drop("MEDV", axis=1) # all the rest
y = boston.MEDV # target variable

In [14]:
# Because of math (notation)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

### Optional train test split parameters

- **`train_size`** is the number that defines the size of the training set. If you provide a float then it must be between 0.0 and 1.0 and will define the part of the dataset used for testing. If you provide an int, then it will represent the total number of training samples. The default value is None.

- **`test_size`** is the number that defines the size of the test suite. It is very similar to train_size. You must provide either train_size or test_size. If neither is provided, the default portion of the dataset to use for testing is 0.25, or 25 percent.

- **`random_state`** is the object that controls randomness during splitting. It can be an int or an instance of RandomState. The default value is None.

### We already have the dataset divided, now we are going to import a model and train it

In [16]:
from sklearn.linear_model import LinearRegression

### We create our predictions

In [17]:
lr = LinearRegression() # y = mx + n

In [18]:
# X_train, x_test, y_train, y_test
# lr

# I WANT TO PREDICT, THE STEPS ARE:
# 1. fit: figure out y = mx +n 
# 2. predict

In [19]:
model = lr.fit(X_train, y_train) # y = 3x  + 4j + 5y + 2

In [20]:
#model_2 = lr.fit(X_train) # Only: we'd be missing the independent variable
# It wouldnt know what to do with the info: 🤷‍

In [21]:
#model_3 = lr.fit(X_test, y_test) # Smaller sample. I want to use the big sample

In [22]:
y_pred = model.predict(X_test)

In [23]:
y_pred[0]

22.57315318752925

In [24]:
model.coef_

array([-8.76635157e-02,  3.61866078e-02,  2.45918552e-02,  2.14016956e+00,
       -1.46158592e+01,  4.99261860e+00, -1.94139759e-02, -1.32186785e+00,
        2.72626428e-01, -1.32686428e-02, -9.54362778e-01,  1.26658479e-02,
       -3.63846736e-01])

In [25]:
model.intercept_

25.62095390387717

### We measure our model

In [26]:
# error: y_pred, y_test
from sklearn import metrics
import numpy as np

In [27]:
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
r2 = metrics.r2_score(y_test, y_pred)

In [28]:
print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R2: {r2}")

MAE: 3.8137760473168023
MSE: 43.52331546318212
RMSE: 6.59722028305726
R2: 0.5413829103498929


#### Mini-checkpoint

- Bias & error: balance underfit or overfit models
- Overfitting: happens when my model explains VERY well ONLY my data
- Underfitting: it doesn't explain very well
- Supervised: labeled data, unsupervised: clustering info, reinforcement
- Deep learning: neural networks
- Train-test split: to evaluate how good our model WOULD BE when presented new data
    - If we don't use train-test (just train with the whole thing instead): we'd be looking at error describing my own data
    - If training with 100%, you might get better or you might overfit
    - You could do 100% to try to only describe too

<img src="https://www.dataquest.io/wp-content/uploads/kaggle_train_test_split.svg" width="500">

## The machine learning process

1. Dataset
2. Processing: encoding, cleaning (NaN), normalization, standarization
3. X, y
4. train-test
5. Split
6. fit/train
7. Predict
8. Look at metrics

#### Example with new data

In [29]:
data = [{"CRIM": 0.247, 
         "ZN": 0.0000, 
         "INDUS": 5.266, 
         "CHAS": 0.001, 
         "NOX": 0.429, 
         "RM": 7.943, 
         "AGE": 50, 
         "DIS": 2.15, 
         "RAD":7.0000, 
         "TAX": 503.25, 
         "PTRATIO": 19.252, 
         "B": 420.35, 
         "LSTAT": 7.6}]

In [30]:
boston.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [31]:
new = pd.DataFrame(data)

In [32]:
new.sample()

CRIM   ZN  INDUS   CHAS    NOX     RM  AGE   DIS  RAD     TAX  PTRATIO  \
0  0.247  0.0  5.266  0.001  0.429  7.943   50  2.15  7.0  503.25   19.252   

        B  LSTAT  
0  420.35    7.6

In [33]:
price = model.predict(new) # prediction

In [34]:
price

array([34.72079541])

## Extra! Training different models at the same time

- [SKlearn - Ridge](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html)
- [SKlearn - Lasso](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html?highlight=lasso#sklearn.linear_model.Lasso)
- [SKlearn - SGD Regressor](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor.html)
- [SKlearn - KNeighbours](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html)
- [SKlearn - GradientBoostingRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingRegressor.html)
- [SKlearn - SVR](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html)

In [35]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.linear_model import SGDRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR

### Store all the models we are going to train in a dictionary

In [36]:
models = {
    "ridge": Ridge(),
    "lasso": Lasso(),
    "SGD": SGDRegressor(),
    "Kneighbours": KNeighborsRegressor(),
    "gbr": GradientBoostingRegressor(),
    "lr": LinearRegression(),
    "svr": SVR()
}

### Iterate over the models to train them

In [37]:
for name, model in models.items():
    print(f"Training 🏋️‍♀️: {name}")
    model.fit(X_train, y_train)

Training 🏋️‍♀️: ridge
Training 🏋️‍♀️: lasso
Training 🏋️‍♀️: SGD
Training 🏋️‍♀️: Kneighbours
Training 🏋️‍♀️: gbr
Training 🏋️‍♀️: lr
Training 🏋️‍♀️: svr


In [38]:
for name, model in models.items():
    y_pred = model.predict(X_test)
    print(f"MAE: {metrics.mean_absolute_error(y_test, y_pred)} for {name}")
    print(f"MSE: {metrics.mean_squared_error(y_test, y_pred)} for {name}")
    print(f"RMSE: {np.sqrt(metrics.mean_squared_error(y_test, y_pred))} for {name}")
    print(f"R2: {metrics.r2_score(y_test, y_pred)} for {name}")
    print("-------")

MAE: 3.829602771594507 for ridge
MSE: 44.195708260851504 for ridge
RMSE: 6.6479852783269235 for ridge
R2: 0.5342977233716699 for ridge
-------
MAE: 4.016872549956073 for lasso
MSE: 41.21838674107186 for lasso
RMSE: 6.420154728748511 for lasso
R2: 0.5656705752746702 for lasso
-------
MAE: 93167288200466.4 for SGD
MSE: 1.139828393655997e+28 for SGD
RMSE: 106762746014515.61 for SGD
R2: -1.2010683814776882e+26 for SGD
-------
MAE: 4.926078431372548 for Kneighbours
MSE: 55.86427843137255 for Kneighbours
RMSE: 7.474240993664343 for Kneighbours
R2: 0.41134280518513267 for Kneighbours
-------
MAE: 2.3028696107497617 for gbr
MSE: 18.572096600614138 for gbr
RMSE: 4.309535543491217 for gbr
R2: 0.8043007339622475 for gbr
-------
MAE: 3.8137760473168023 for lr
MSE: 43.52331546318212 for lr
RMSE: 6.59722028305726 for lr
R2: 0.5413829103498929 for lr
-------
MAE: 5.939651080013242 for svr
MSE: 86.48135790724614 for svr
RMSE: 9.2995353597503 for svr
R2: 0.08872225724711147 for svr
-------


In [39]:
#R2: 0.9262741564523895 for gbr

In [40]:
data

[{'CRIM': 0.247,
  'ZN': 0.0,
  'INDUS': 5.266,
  'CHAS': 0.001,
  'NOX': 0.429,
  'RM': 7.943,
  'AGE': 50,
  'DIS': 2.15,
  'RAD': 7.0,
  'TAX': 503.25,
  'PTRATIO': 19.252,
  'B': 420.35,
  'LSTAT': 7.6}]

In [41]:
gbr = GradientBoostingRegressor()

In [42]:
gbr_fit = gbr.fit(X_train, y_train)

In [43]:
y_pre = gbr_fit.predict(X_test)

In [44]:
new_dataframe = pd.DataFrame(data)
new_dataframe

CRIM   ZN  INDUS   CHAS    NOX     RM  AGE   DIS  RAD     TAX  PTRATIO  \
0  0.247  0.0  5.266  0.001  0.429  7.943   50  2.15  7.0  503.25   19.252   

        B  LSTAT  
0  420.35    7.6

In [45]:
y_pre = gbr_fit.predict(new_dataframe)
y_pre

array([36.47155495])

## Feature Selection

[](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html?highlight=rfe#sklearn.feature_selection.RFE)

[Docs](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFromModel.html)

In [46]:
from sklearn.feature_selection import RFE

In [59]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, step=1)
selector = selector.fit(X_test, y_test)
selector.support_

array([False, False, False,  True,  True,  True, False,  True, False,
       False,  True, False,  True])

In [60]:
selector.ranking_

array([2, 4, 8, 1, 1, 1, 6, 1, 3, 5, 1, 7, 1])

In [61]:
selector.n_features_

6

In [50]:
boston.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

Given an external estimator that assigns weights to features (for example, the coefficients of a linear model), the goal of recursive feature elimination (RFE) is to select them by recursively considering smaller and smaller sets of features. First, the estimator is trained with the initial set of features and the importance of each of them is obtained through some specific or callable attribute. The less important features of the current set are then removed. This procedure is repeated recursively on the pruned set until the desired number of features to select is reached.

The ranking of the features, so that ranking_[i] corresponds to the ranking position of the i-th feature. Selected features (i.e. best estimates) are assigned rank 1.

In [51]:
# The metrics for cross validation are R2 for regression and Accuracy for classification

![kfoldcv](https://scikit-learn.org/stable/_images/grid_search_cross_validation.png)

Cross-Validation: K-fold with 5 splits
What we normally do when training the model is to pass all the records to it and have it do the fit().
With K-Folds -in this example of 5 splits- to train, instead of passing all the records directly to the model, we will do this:

**Iterate 5 times:**
- We will set aside 1/5 of samples
- We train the model with the remaining 4/5 samples
- We will measure the r2 obtained on those we had set aside.
- This means that we do 5 independent workouts.
- The final R2 will be the average of the 5 previous R2.

### We make CV to a single model

In [52]:
from sklearn.model_selection import cross_val_score as cvs

In [53]:
models

{'ridge': Ridge(),
 'lasso': Lasso(),
 'SGD': SGDRegressor(),
 'Kneighbours': KNeighborsRegressor(),
 'gbr': GradientBoostingRegressor(),
 'lr': LinearRegression(),
 'svr': SVR()}

In [54]:
another = models["gbr"]
another

GradientBoostingRegressor()

In [55]:
scores = cvs(another, X, y, scoring="r2", cv=3)

In [56]:
scores

array([0.81960042, 0.63445132, 0.27916462])

In [57]:
np.mean(scores)

0.5777387855753012

### CV looping through all models

In [58]:
for name, model in models.items():
    scores = cvs(model, X, y, scoring="r2", cv=6)
    print("Model: ", name, "Score ", np.mean(scores))

Model:  ridge Score  0.4195152192677214
Model:  lasso Score  0.4207356091521697
Model:  SGD Score  -3.609142924046162e+26
Model:  Kneighbours Score  -0.38655462832426896
Model:  gbr Score  0.6744677081741838
Model:  lr Score  0.4001944881138579
Model:  svr Score  -0.11651286665089305


![kfoldcv](https://scikit-learn.org/stable/_images/grid_search_cross_validation.png)

## Summary

Trying to predict something based on data

- Data
    - Variables
    - Features: more or less
- Models
    - lr
    - gradientboosting
    - ...
- Param 
    - ...
- Split
    - cross-validation

# THE WHOLE PROCESS: goal predict from new info

1. Dataset
2. Processing of the data: "rock" 
    - cleaning np.nan
    - categorical encoding: get_dummies
    - standarization & normalization
3. X, y
4. Split
5. model: fit(X_train, y_train)
6. y_pred = predict(X_test)
7. compare y_test, y_pred -> error metrics

8. Do this for other models
9. Choose a model

10. RFE: recursive feature elimination
11. Split data into difrerent ways: using cvs
