# Intro to Machine Learning

![elgifderigor](https://media.giphy.com/media/NsBknNwmmWE8WU1q2U/giphy.gif)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Some-concepts" data-toc-modified-id="Some-concepts-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Some concepts</a></span><ul class="toc-item"><li><span><a href="#Estimators" data-toc-modified-id="Estimators-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Estimators</a></span></li><li><span><a href="#Bias-Error" data-toc-modified-id="Bias-Error-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Bias Error</a></span></li><li><span><a href="#Variance-Error" data-toc-modified-id="Variance-Error-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Variance Error</a></span></li></ul></li><li><span><a href="#Types-of-Machine-Learning" data-toc-modified-id="Types-of-Machine-Learning-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Types of Machine Learning</a></span></li><li><span><a href="#Features" data-toc-modified-id="Features-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Features</a></span></li><li><span><a href="#Underfitting-and-Overfitting" data-toc-modified-id="Underfitting-and-Overfitting-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Underfitting and Overfitting</a></span></li><li><span><a href="#Let's-do-it?" data-toc-modified-id="Let's-do-it?-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Let's do it?</a></span><ul class="toc-item"><li><span><a href="#Let's-practice-ML-with-a-regression-example" data-toc-modified-id="Let's-practice-ML-with-a-regression-example-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Let's practice ML with a regression example</a></span></li><li><span><a href="#We-load-a-dataset" data-toc-modified-id="We-load-a-dataset-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>We load a dataset</a></span></li><li><span><a href="#Train-/-Test-Split---What-is-this?" data-toc-modified-id="Train-/-Test-Split---What-is-this?-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Train / Test Split - What is this?</a></span></li><li><span><a href="#Preparing-data-for-train-test-split" data-toc-modified-id="Preparing-data-for-train-test-split-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Preparing data for train test split</a></span></li><li><span><a href="#Optional-train-test-split-parameters" data-toc-modified-id="Optional-train-test-split-parameters-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Optional train test split parameters</a></span></li><li><span><a href="#We-already-have-the-dataset-divided,-now-we-are-going-to-import-a-model-and-train-it" data-toc-modified-id="We-already-have-the-dataset-divided,-now-we-are-going-to-import-a-model-and-train-it-5.6"><span class="toc-item-num">5.6&nbsp;&nbsp;</span>We already have the dataset divided, now we are going to import a model and train it</a></span></li><li><span><a href="#We-create-our-predictions" data-toc-modified-id="We-create-our-predictions-5.7"><span class="toc-item-num">5.7&nbsp;&nbsp;</span>We create our predictions</a></span></li><li><span><a href="#We-measure-our-model" data-toc-modified-id="We-measure-our-model-5.8"><span class="toc-item-num">5.8&nbsp;&nbsp;</span>We measure our model</a></span><ul class="toc-item"><li><span><a href="#Example-with-a-real-case-of-a-colleague-who-gives-me-data-from-a-house-in-Boston" data-toc-modified-id="Example-with-a-real-case-of-a-colleague-who-gives-me-data-from-a-house-in-Boston-5.8.1"><span class="toc-item-num">5.8.1&nbsp;&nbsp;</span>Example with a real case of a colleague who gives me data from a house in Boston</a></span></li></ul></li></ul></li><li><span><a href="#Extra!-Training-different-models-at-the-same-time" data-toc-modified-id="Extra!-Training-different-models-at-the-same-time-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Extra! Training different models at the same time</a></span><ul class="toc-item"><li><span><a href="#Store-all-the-models-we-are-going-to-train-in-a-dictionary" data-toc-modified-id="Store-all-the-models-we-are-going-to-train-in-a-dictionary-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Store all the models we are going to train in a dictionary</a></span></li><li><span><a href="#Iterate-over-the-models-to-train-them" data-toc-modified-id="Iterate-over-the-models-to-train-them-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Iterate over the models to train them</a></span></li></ul></li><li><span><a href="#Feature-Selection" data-toc-modified-id="Feature-Selection-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Feature Selection</a></span><ul class="toc-item"><li><span><a href="#We-make-CV-to-a-single-model" data-toc-modified-id="We-make-CV-to-a-single-model-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>We make CV to a single model</a></span></li><li><span><a href="#CV-looping-through-all-models" data-toc-modified-id="CV-looping-through-all-models-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>CV looping through all models</a></span></li></ul></li><li><span><a href="#Summary" data-toc-modified-id="Summary-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Summary</a></span></li></ul></div>

## Some concepts
To understand how a machine learning algorithm learns from data to predict an outcome, it is essential to understand the underlying concepts that go into training an algorithm.

### Estimators
Estimate is a statistical term for finding some estimate of an unknown parameter, given some data. Point estimation is the attempt to provide the best prediction of some quantity of interest.
The amount of interest can be:
 - A single parameter
 - A vector of parameters - for example, the weights in linear regression
 - A full function

### Bias Error

It is the difference between the expected prediction of our model and the true values. Although in the end our goal is always to build models that can predict data very close to the true values, it is not always that easy because some algorithms are simply too rigid to learn complex signals from the data set.

Imagine fitting a linear regression to a data set that has a non-linear pattern, no matter how many more observations you collect, a linear regression will not be able to model the curves on that data. This is known as underfitting.

In general, parametric algorithms like linear regression have a high bias that makes them quick to learn and easier to understand, but generally less flexible. In turn, they have a lower predictive performance in complex problems.

### Variance Error

It refers to the amount that the estimate of the objective function will change if different training data is used. The objective function is estimated from the training data by a Machine Learning algorithm, so we should expect the algorithm to have some variance. Ideally it shouldn't change too much from one training dataset to another, which means the algorithm is good at choosing the hidden underlying mapping between the input and output variables.

Machine learning algorithms that have a large variance are heavily influenced by the details of the training data, this means that the details of the training influence the number and types of parameters used to characterize the mapping function.

Generally, non-parametric machine learning algorithms that have a lot of flexibility have a lot of variation.

- Low variance: suggests small changes in the estimate of the objective function with changes in the training data set.
- High variance: suggests large changes in the estimate of the objective function with changes in the training data set.
Low variance machine learning algorithms include: linear regression, linear discriminant analysis, and logistic regression.

On the other hand, the algorithms with high variance are: decision trees, k-nearest neighbors and support vector machines.

<img src="https://nvsyashwanth.github.io/machinelearningmaster/assets/images/bias_variance.jpg" width="400">

## Types of Machine Learning
- **Supervised**
The model is trained with labeled data, that is, with data whose basic truth is known. When presented with data and a label, the model infers patterns.

- **Unsupervised**
There are no basic truths. The model looks for previously undetected patterns, with which to separate the different data points into different clusters.

- **Reinforcement**
There is also no basic truth. The model's action is valued and a reward or punishment is given accordingly. The goal of the model is to get as many rewards as possible.

## Features
- **Features** are independent individual variables that act as input to your system. Prediction models use features to
make predictions.

- **Target**
The goal is the output of the input variables. They can be the individual classes to which the input variables are assigned in the case of a classification problem or the range of output values ​​in a regression problem.

## Underfitting and Overfitting
Splitting a data set can also be important to detect if your model suffers from one of two common problems, called underfitting and overfitting:

- **Underfitting** is usually the consequence of a model being unable to encapsulate relationships between data. For example, this can occur when trying to represent nonlinear relationships with a linear model. Underfitted models are likely to perform poorly on both the training and test sets.


- **Overfitting** usually occurs when a model has an excessively complex structure and learns both relationships between data and noise. These models tend to have poor generalization ability. Although they work well with training data, they tend to perform poorly with unseen (test) data.

<img src="https://community.alteryx.com/t5/image/serverpage/image-id/52874iE986B6E19F3248CF?v=v2" width="500">

Bias and variance in machine learning --> https://www.analyticslane.com/2019/05/24/the-concepts-of-bias-and-variance-in-machine-learning/

## Let's do it?

### Let's practice ML with a regression example

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
from sklearn.datasets import load_boston

### We load a dataset

In [3]:
help(load_boston)

Help on function load_boston in module sklearn.datasets._base:

load_boston(*, return_X_y=False)
    DEPRECATED: `load_boston` is deprecated in 1.0 and will be removed in 1.2.
    
    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.
    
    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.
    
    In this special case, you can fetch the dataset from the original
    source::
    
        import pandas as pd
        import numpy as np
    
        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]
    
    Alternative datasets include the California housing 

In [4]:
boston = pd.DataFrame(load_boston().data, columns=load_boston().feature_names)

In [5]:
boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [6]:
boston["MEDV"] = load_boston().target # Target variable

In [7]:
boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

### Train / Test Split - What is this?

<img src="https://www.dataquest.io/wp-content/uploads/kaggle_train_test_split.svg" width="500">

The training-test split is a technique for evaluating the performance of a machine learning algorithm.

It can be used for classification or regression problems and can be used for any supervised learning algorithm.

The procedure consists of taking a data set and dividing it into two subsets. The first subset is used to fit the model and is called the training data set. The second subset is not used to train the model; instead, the model is given the input from the dataset, then predictions are made and compared to expected values. This second data set is called the test data set.

Training dataset: Used to fit the machine learning model.
Test dataset: Used to evaluate the fitted machine learning model.
The goal is to estimate the performance of the machine learning model with new data: data not used to train the model.

This is how we hope to use the model in practice. That is, fit it on the available data with known inputs and outputs, and then make predictions about new examples in the future where we don't have the expected output or target values.

The training-test procedure is adequate when a sufficiently large data set is available.

### Preparing data for train test split

In [8]:
boston.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [9]:
X = boston.drop("MEDV", axis=1) #The X is always a dataframe (Even if it only has one column)
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [10]:
y = boston.MEDV #La y is always A PANDAS SERIES
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: MEDV, dtype: float64

In [11]:
X.shape

(506, 13)

In [12]:
y.shape

(506,)

### Optional train test split parameters

- **`train_size`** is the number that defines the size of the training set. If you provide a float then it must be between 0.0 and 1.0 and will define the part of the dataset used for testing. If you provide an int, then it will represent the total number of training samples. The default value is None.

- **`test_size`** is the number that defines the size of the test suite. It is very similar to train_size. You must provide either train_size or test_size. If neither is provided, the default portion of the dataset to use for testing is 0.25, or 25 percent.

- **`random_state`** is the object that controls randomness during splitting. It can be an int or an instance of RandomState. The default value is None.

In [13]:
from sklearn.model_selection import train_test_split as tts

In [14]:
#help(tts) # sklearn help

In [15]:
X_train, X_test, y_train, y_test = tts(X,y, test_size=0.2)

In [16]:
X_train.shape

(404, 13)

In [17]:
X_test.shape

(102, 13)

In [18]:
y_train.shape

(404,)

In [19]:
y_test.shape

(102,)

### We already have the dataset divided, now we are going to import a model and train it

In [20]:
from sklearn.linear_model import LinearRegression as LinReg

In [21]:
linreg=LinReg()

In [22]:
linreg

LinearRegression()

In [23]:
linreg.fit(X_train, y_train) # Training

LinearRegression()

In [24]:
linreg.coef_ # betas coefficients

array([-1.25546425e-01,  4.80526273e-02,  4.77534406e-03,  2.78292708e+00,
       -1.57625323e+01,  4.10384314e+00, -8.83064530e-03, -1.48642629e+00,
        3.15230956e-01, -1.39024146e-02, -8.68109730e-01,  9.37030005e-03,
       -4.68757235e-01])

In [25]:
linreg.intercept_

32.762655041306196

### We create our predictions

In [26]:
y_pred = linreg.predict(X_test)

In [27]:
y_pred.shape

(102,)

### We measure our model

In [28]:
from sklearn import metrics
import numpy as np

In [29]:
print('MAE - Mean absolute error', metrics.mean_absolute_error(y_test, y_pred))
print('MSE - Mean squared error', metrics.mean_squared_error(y_test, y_pred))
print('RMSE - Root mean squared error', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R2 - Coefficient of determination', metrics.r2_score(y_test, y_pred))

MAE - Mean absolute error 3.1990164957150267
MSE - Mean squared error 22.948748187750336
RMSE - Root mean squared error 4.790485172479959
R2 - Coefficient of determination 0.7279325655991955


In [30]:
X_test.iloc[0] #Example of a sample of my data

CRIM         0.57529
ZN           0.00000
INDUS        6.20000
CHAS         0.00000
NOX          0.50700
RM           8.33700
AGE         73.30000
DIS          3.83840
RAD          8.00000
TAX        307.00000
PTRATIO     17.40000
B          385.91000
LSTAT        2.47000
Name: 232, dtype: float64

#### Example with a real case of a colleague who gives me data from a house in Boston

In [35]:
data = [{"CRIM": 0.247, "ZN": 0.0000, "INDUS": 5.266, "CHAS": 0.001, "NOX": 0.429, "RM": 7.943, "AGE": 50, "DIS": 2.15, "RAD":7.0000, "TAX": 503.25, "PTRATIO": 19.252, "B": 420.35, "LSTAT": 7.6}]

In [36]:
new = pd.DataFrame(data)

In [37]:
new

CRIM   ZN  INDUS   CHAS    NOX     RM  AGE   DIS  RAD     TAX  PTRATIO  \
0  0.247  0.0  5.266  0.001  0.429  7.943   50  2.15  7.0  503.25   19.252   

        B  LSTAT  
0  420.35    7.6

In [38]:
price = linreg.predict(new) # I GET THE PREDICTION WITH MY NEW DATA

In [39]:
price

array([33.83055452])

## Extra! Training different models at the same time

- [SKlearn - Ridge](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html)
- [SKlearn - Lasso](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html?highlight=lasso#sklearn.linear_model.Lasso)
- [SKlearn - SGD Regressor](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor.html)
- [SKlearn - KNeighbours](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html)
- [SKlearn - GradientBoostingRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingRegressor.html)
- [SKlearn - SVR](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html)

In [60]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.linear_model import SGDRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR

### Store all the models we are going to train in a dictionary

In [41]:
models = {
    'ridge': Ridge(),
    'lasso': Lasso(),
    'sgd': SGDRegressor(),
    'knn': KNeighborsRegressor(),
    'grad': GradientBoostingRegressor(),
}

In [42]:
model = Ridge()

In [43]:
type(model)

sklearn.linear_model._ridge.Ridge

### Iterate over the models to train them

In [44]:
for name, model in models.items():
    print("Training 🏋️‍♀️: ", name)
    model.fit(X_train, y_train)

Training 🏋️‍♀️:  ridge
Training 🏋️‍♀️:  lasso
Training 🏋️‍♀️:  sgd
Training 🏋️‍♀️:  knn
Training 🏋️‍♀️:  grad


In [45]:
# We can follow the same process to make predictions from each algorithm and get metrics
for name, model in models.items():z5
    y_pred = model.predict(X_test)
    print(f"------{name}------")
    print('MAE - ', metrics.mean_absolute_error(y_test, y_pred))
    print('MSE - ', metrics.mean_squared_error(y_test, y_pred))
    print('RMSE - ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
    print('R2 - ', metrics.r2_score(y_test, y_pred))

------ridge------
MAE -  3.2488989854329575
MSE -  23.471782243089603
RMSE -  4.844768543809869
R2 -  0.7217317683977011
------lasso------
MAE -  3.7506318106230063
MSE -  26.407376998936343
RMSE -  5.138810854559287
R2 -  0.6869290102198062
------sgd------
MAE -  256412889944270.16
MSE -  7.098130245723041e+28
RMSE -  266423164265479.0
R2 -  -8.415143471866784e+26
------knn------
MAE -  4.398235294117647
MSE -  35.20094509803922
RMSE -  5.933038437262919
R2 -  0.5826774191361268
------grad------
MAE -  2.0480367550963297
MSE -  6.984801078227538
RMSE -  2.642877423988396
R2 -  0.9171921320672425


In [46]:
#help(GradientBoostingRegressor())

## Feature Selection

In [47]:
from sklearn.feature_selection import RFE

[Docs](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFromModel.html)

Given an external estimator that assigns weights to features (for example, the coefficients of a linear model), the goal of recursive feature elimination (RFE) is to select them by recursively considering smaller and smaller sets of features. First, the estimator is trained with the initial set of features and the importance of each of them is obtained through some specific or callable attribute. The less important features of the current set are then removed. This procedure is repeated recursively on the pruned set until the desired number of features to select is reached.

In [48]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=5, step=1)
selector = selector.fit(X_test, y_test)
selector.support_

array([False, False, False,  True,  True,  True, False,  True, False,
       False,  True, False, False])

In [49]:
selector.ranking_

array([5, 8, 4, 1, 1, 1, 6, 1, 3, 9, 1, 7, 2])

The ranking of the features, so that ranking_[i] corresponds to the ranking position of the i-th feature. Selected features (i.e. best estimates) are assigned rank 1.

In [50]:
# The metrics for cross validation are R2 for regression and Accuracy for classification

![kfoldcv](https://scikit-learn.org/stable/_images/grid_search_cross_validation.png)

Cross-Validation: K-fold with 5 splits
What we normally do when training the model is to pass all the records to it and have it do the fit().
With K-Folds -in this example of 5 splits- to train, instead of passing all the records directly to the model, we will do this:

**Iterate 5 times:**
- We will set aside 1/5 of samples
- We train the model with the remaining 4/5 samples
- We will measure the r2 obtained on those we had set aside.
- This means that we do 5 independent workouts.
- The final R2 will be the average of the 5 previous R2.

### We make CV to a single model

In [51]:
from sklearn.model_selection import cross_val_score as cvs

In [52]:
models

{'ridge': Ridge(),
 'lasso': Lasso(),
 'sgd': SGDRegressor(),
 'knn': KNeighborsRegressor(),
 'grad': GradientBoostingRegressor()}

In [53]:
gradient = models["grad"] # store the model in a variable that previously had it in a dictionary

In [54]:
scores = cvs(gradient, X, y, scoring="r2", cv=3)

In [55]:
scores

array([0.80795678, 0.6457523 , 0.28269438])

In [56]:
np.mean(scores)

0.5788011556510301

### CV looping through all models

In [57]:
for name, model in models.items():
    scores = cvs(model, X, y, scoring='r2', cv=5)
    print('Model: ', name, 'Score: ', np.mean(scores))

Modelo:  ridge Score:  0.3892175824102393
Modelo:  lasso Score:  0.431848787926522
Modelo:  sgd Score:  -3.517371768618188e+26
Modelo:  knn Score:  -0.31501646812514134
Modelo:  grad Score:  0.6760512717769519


## Summary

- Machine learning
- train test split --> (X_train, y_train, X_test, y_test)
- three types of ML (supervised, unsupervised, by reinforcement)
- y_pred --> the predictions I make with the model (model.predict(X_test))
- model.fit(X_train,y_train) --> learn the data
- ground truth --> and my target variable, is what makes it SUPERVISED
- most important features / characteristics (variables that most influence the explanation of my data)
- target == and
- X == all my features (columns)